### ISSUE TITLE
Ce référentiel est-il toujours maintenu ?  Is this repository still maintained?

### ISSUE THREAD

**Issue by zrfisaac** [odalet/Hawkeye2#13]
Bonjour, j'aimerais ajouter de nouvelles fonctionnalités et je veux savoir si vous @odalet maintenez toujours ce référentiel pour vous envoyer des pull requests ou si je crée un nouveau référentiel.

Hi, I'd like to add some new features and I wanna know if you @odalet still maintain this repository to send you some pull requests or if I create a new repository.

**Comment by odalet** [comment]
Hi Isaac!

As you've seen, this repository is indeed an old project I'm no longer working on. 

For a bit of history, I'm not the original author (Some Corneliu I. Tusnea from Australia created this at a time when Codeplex was the latest hype!). I was first a user of the project, then when he stopped maintaining it, I forked it (first on Codeplex, then here on Github), it served me well and I had some fun with it, but it's been now a few years since I needed it. It's also a bit of a pain in the a** to (fully) build it as the .NET 2 version requires VS2008 for the C++/CLI part, but that's probably something you can safely get rid of (The original project even had .NET 1 compatibility!)...

Anyway, if you need additional features, sure go fork it. And if you feel you can take over and maintain it from now on, feel free to do so: Just drop me a message here when you are ready; I'll archive this repository and update the Readme so that people know Hawkeye's new home is **your** repository.

PS: Btw, thanks for the French translation effort, much appreciated! Then I deeply enjoy using English here (I like the language and it helps me practice)

**Comment by zrfisaac** [comment]
Hi!
Thanks for the reply.
I also prefer to speak in english and portuguese. I don't speak french even though to me it is one of the most beautiful languages.
But Yes indeed, I pretend to maintain and add some new features that I need.
Soon I will post some stuff on the [Hawkeye3](https://github.com/zrfisaac/Hawkeye3) repository. I'd like to start this weekend but I have some work to do from my job.
Anyway, thank you for the reply and I will continue to maintain this project!
:raised_hands: :raised_hands: :raised_hands: :raised_hands: :raised_hands:

**Comment by odalet** [comment]
Had a look at your repo. Now archiving this one and redirecting to yours!

PS: I'm not the best judge of French language as it's my native tongue, but if deem it a bit too flat, too plain... I love the musicality of English, Italian or... Portuguese: I've been watching this (very good) show from Brazil, [3%](https://en.wikipedia.org/wiki/3%25) and the language was music to my hears!
